name: fake-news
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38haf1e3a3_1000
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.0=py38hc512035_1
  - chardet=3.0.4=py38_1003
  - cryptography=2.9.2=py38ha12b0ac_0
  - cycler=0.10.0=py38_0
  - freetype=2.10.2=ha233b18_0
  - idna=2.10=py_0
  - intel-openmp=2019.4=233
  - joblib=0.16.0=py_0
  - jpeg=9b=he5867d9_2
  - kiwisolver=1.2.0=py38h04f5b5a_0
  - lcms2=2.11=h92f6f08_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.1.0=hcb84e12_1
  - llvm-openmp=10.0.0=h28b9765_0
  - lz4-c=1.9.2=hb1e8313_1
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py38h5670ca0_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py38hfbe908c_0
  - mkl_fft=1.1.0=py38hc64f4ea_0
  - mkl_random=1.1.1=py38h959d312_0
  - ncurses=6.2=h0a44026_1
  - ninja=1.10.0=py38h879752b_0
  - numpy=1.18.5=py38h1da2735_0
  - numpy-base=1.18.5=py38h3304bdc_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h1de35cc_0
  - pandas=1.0.5=py38h959d312_0
  - pillow=7.2.0=py38ha54b6ba_0
  - pip=20.1.1=py38_1
  - pycparser=2.20=py_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pysocks=1.7.1=py38_1
  - python=3.8.3=h26836e1_2
  - python-dateutil=2.8.1=py_0
  - pytorch=1.6.0=py3.8_0
  - pytz=2020.1=py_0
  - readline=8.0=h1de35cc_0
  - requests=2.24.0=py_0
  - scikit-learn=0.23.1=py38h603561c_0
  - scipy=1.5.0=py38hbab996c_0
  - setuptools=49.2.0=py38_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=hffcf06c_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hb0a8c7a_0
  - torchtext=0.7.0=py38
  - torchvision=0.7.0=py38_cpu
  - tornado=6.0.4=py38h1de35cc_1
  - tqdm=4.47.0=py_0
  - urllib3=1.25.9=py_0
  - wheel=0.34.2=py38_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
prefix: /usr/local/Caskroom/miniconda/base/envs/fake-news

